name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: sast scan
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest

    - name: Run horusec
      run: |
        horusec start -P 'Democracy.xcodeproj' -a ${{ secrets.TEST_TOKEN }} 
