name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: sast scan
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Horusec
      id: run_horusec
      uses: fike/horusec-action@v0.1
      with:
        arguments: --config-file-path=horusec-config.json
