name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: macos-latest
    name: sast scan
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
        horusec -v

    - name: Run horusec
      run: |
        horusec start -p . -o horusec-report.html -f html
        ls
